Meetings-Channel: implement a basic filter
ksdfg/Meetings-Channel pull request #1
Opened 2020-11-11 14:08 UTC by akhilnarang

2020-11-11 14:09 UTC, akhilnarang commented
Untested, just a rough idea of what I thought would work
Could definitely use some improvements

2020-11-11 15:57 UTC, ksdfg requested changes
Can you add a small brief in the README to explain how this will work?

2020-11-12 08:43 UTC, ksdfg requested changes
- Try using `cast=CSV()`  for getting list of whitelisted/blacklisted words; check how I'm fetching `links_to_check` for reference.

- It would be better to have filter as `blacklist` in the sample config file instead of whitelist so without any changes to the sample config it'll still send all links

2020-11-17 12:45 UTC, ksdfg approved these changes

2020-11-17 12:46 UTC, merged